# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewId', models.BigIntegerField()),
                ('startDate', models.CharField(max_length=16)),
                ('endDate', models.CharField(max_length=16)),
                ('width', models.IntegerField(default=1280)),
                ('height', models.IntegerField(default=480)),
            ],
        ),
        migrations.CreateModel(
            name='Lost_site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=160)),
                ('viewId', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32)),
                ('ru', models.CharField(max_length=48)),
                ('en', models.CharField(max_length=48)),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebService.Metric'),
        ),
    ]
