# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0002_chart_max_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={'ordering': ['numb']},
        ),
        migrations.AddField(
            model_name='chart',
            name='numb',
            field=models.IntegerField(default=1),
        ),
    ]
