# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebService', '0004_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='height',
            field=models.IntegerField(default=480),
        ),
        migrations.AddField(
            model_name='chart',
            name='width',
            field=models.IntegerField(default=1280),
        ),
    ]
